added condtion to check only ip is added

diff --git a/.github/workflows/create_ec2.yml b/.github/workflows/create_ec2.yml
--- a/.github/workflows/create_ec2.yml
+++ b/.github/workflows/create_ec2.yml
@@ -76,8 +76,14 @@ jobs:
       - name: Get EC2 Public IP from Terraform Output
         id: get_ip
         run: |
-            IP=$(terraform output -raw ec2_public_ip)
-            echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV
+            IP=$(terraform output -raw ec2_public_ip 2>/dev/null)
+            if [[ "$IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "EC2_PUBLIC_IP=$IP"
+              echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV
+            else
+              echo "Invalid IP output: $IP"
+              exit 1
+            fi
     
       - name: Store EC2 Public IP in SSM Parameter Store
         run: |
